apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6yqk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-6yqk@sha256:66dbaa23b4d9383e07c2acfc053bb757aa582bbf49f6aab8dc4d2e28bd478e0f
        name: my-nodejs
        resources: {}
status: {}
